---
- name: Install prereq. pkg
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present
  tags: auditbeat

- name: Add ElasticSearch repo key
  ansible.builtin.apt_key:
    url: "{{ es_apt_key }}"
    state: present
  tags: auditbeat

- name: Add ElasticSearch repository
  ansible.builtin.apt_repository:
    repo: "{{ es_apt_url }}"
    state: present
  tags: auditbeat

- name: Auditbeat | Apt pinning for pkgs
  ansible.builtin.template:
    src: "pinning.j2"
    dest: "/etc/apt/preferences.d/{{ item.name }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ es_auditbeat_pinning_pkgs }}"
  when:
    - es_auditbeat_pinning_pkgs is defined
  tags: auditbeat

- name: Install auditbeat package
  ansible.builtin.apt:
    name: auditbeat
    state: present
  tags: auditbeat

- name: Create main auditbeat config
  ansible.builtin.template:
    src: "auditbeat.yml.j2"
    dest: "/etc/auditbeat/auditbeat.yml"
    owner: root
    group: root
    mode: 0600
  notify: restart auditbeat
  tags: auditbeat

- name: Enable and start auditbeat service
  ansible.builtin.service:
    name: auditbeat
    enabled: true
    state: started
  tags: auditbeat
...
